### PR TITLE
Create KeltnerChannelsTests.cs

### PR DESCRIPTION
**Pull request by lockyssmith**
Tester file for keltner channels

### CODE REVIEW

**Comment by mchandschuh** [comment]
I'll merge this along with the other keltner PRs into one commit on master.

**Comment by mchandschuh** [comment]
After pulling all the code down locally ( #160, #161, #162, #163 ) I was able to get it to build (moved KelterChannels.cs to Indicators and added to csproj). I added KeltnerChannels.cs to QuantConnect.Tests.csproj and I also added spy_with_keltner.csv to the QuantConnect.Tests.csproj and set it to copy if newer. 

After these steps I was unable to get the tests to pass. I tried setting the epsilon on the Assert statements to 0.1 ( I wouldn't like to allow more error than that ) and they still failed. We'll need to take another look at the implementation to verify before pushing into master.

**Comment by lockyssmith** [comment]
I had verified the outputs previously. There may be a difference due to spy test data using a different number of ATR multiples. In the tester I had used 20 periods and 1.5 multiples. Would need to confirm with jared what multiple he used when setting up the test data.

**Comment by jaredbroad** [comment]
@lockyssmith - I just used the default value from freestockcharts.com (20
typical price / 1.5 atr multiple)

On Wed, Sep 9, 2015 at 5:52 PM, lockyssmith <notifications@github.com>
wrote:

> I had verified the outputs previously. There may be a difference due to
> spy test data using a different number of ATR multiples. In the tester I
> had used 20 periods and 1.5 multiples. Would need to confirm with jared
> what multiple he used when setting up the test data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QuantConnect/Lean/pull/162#issuecomment-139056463>.
>



-- 
Jared Broad

www.quantconnect.com
Phone-USA: +1 917 327 0556
*Democratizing Finance, Empowering Individuals*
Facebook <http://www.facebook.com/QuantConnect> | Twitter
<https://twitter.com/#!/QuantConnect> | LinkedIn
<http://www.linkedin.com/company/quantconnect> | Skype: jaredbroad

**Comment by mchandschuh** [comment]
Merged in Keltner Channels in https://github.com/QuantConnect/Lean/commit/b79431a8c912f1aa23ed3fde852a2a03f490417d

**Pull request closed without merging**
