### PR TITLE
Python Package Addition - Deap

### PR DESCRIPTION
**Pull request by DMTSource**
Added pip installation instruction to DockerfileLeanFoundation for DEAP(Distributed Evolutionary Algorithms in Python).

[DEAP Github](https://github.com/DEAP/deap)
[Documentation & Tutorials](http://deap.readthedocs.io/en/master/)

### CODE REVIEW

**Comment by AlexCatarino** [comment]
I would like to see this package in action in a simple algorithm so that we could include it as an example.

**Comment by DMTSource** [comment]
@AlexCatarino I have a Basic Genetic Programming and a Basic Genetic Algorithm based on the Deap Turorials near ready to go for the python example folder, but I wanted to test them on the cloud & add a few more assets to make them more interesting. I will share them asap.

**Comment by AlexCatarino** [comment]
Great, @DMTSource!
We can have a simpler algorithm in Lean and you could share a more interesting one, in the forum. You could also write a tutorial on using DEAP on Lean!
Am I asking too much? :) 
Thank you!

**Comment by jaredbroad** [comment]
Simple "Basic Template DEAP" would be helpful; + addition to the package regression algorithm; 
https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/PythonPackageTestAlgorithm.py

**Comment by jaredbroad** [comment]
Closing for now @DMTSource; if you can please re-submit with the package test lines so it can be covered by regression tests =)

**Pull request closed without merging**
