### PR TITLE
Feature 3533 improve extensibility framework fillmodel

### LINKED ISSUE #3533: Improve extensibility for algorithm framework and fill model
#### Expected Behavior

Certain methods in QCAlgorithm and FillModel classes are useful for fine-tuning behavior in sub-classes:

FillModel.GetPricesCheckingPythonWrapper
FillModel.IsExchangeOpen
QCAlgorithm.Framework.OnInsightsGenerated
QCAlgorithm.Framework.InitializeInsightFields
QCAlgorithm.Framework.ProcessInsights

#### Actual Behavior

Methods are private.

#### Potential Solution

Make methods accessible in sub-classes.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### PR DESCRIPTION
**Pull request by olegsheyner**
Make some methods accessible to sub-classes

#### Related Issue

Closes #3533 

#### Motivation and Context

Improve ability to fine-tune fill models and algorithm framework flow in sub-classes.

#### How Has This Been Tested?

Regression tests pass.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by Martin-Molinero** [comment]
Hi @olegsheyner,
Could you please provide a detailed use case/requirement for each of these changes, so we assert, evaluate and document them - The one I can understand is `FillModel.IsExchangeOpen`.
`FillModel.GetPricesCheckingPythonWrapper` was added for C# base methods used by a python custom `FillModel`. `Algorithm.ProcessInsights()` is the core framework pipeline structure. `Algorithm.OnInsightsGenerated()` is also part of the insight pipeline. I believe `Algorithm.InitializeInsightFields()` is private to guarantee the prices and times of an insight are set right.
Thanks!

**Comment by olegsheyner** [comment]
Hi @Martin-Molinero,

Regarding `FillModel': looking to tweak certain aspects of `FillModel`, while leaving the rest of the behavior unchanged.  As a specific example, base implementation of `MarketOnOpenFill` references `GetPricesCheckingPythonWrapper` - would be ideal for the subtype implementation to continue getting prices in the same manner.

Regarding `Algorithm`, the use case is as follows.  External events, not tied to or easily represented as time series data, generate insights.  It is useful to initiate insight generation/processing cycle as triggered by outside events, but the standard framework algorithm runs only universe selection and skips insight generation if the data slice has no data.

The use case could be satisfied by extracting the insight generation/processing cycle code at the end of OnFrameworkData into a separate method and making this method available in sub-classes:

```
            var insightsEnumerable = Alpha.Update(this, slice);
            // for performance only call 'ToArray' if not empty enumerable (which is static)
            var insights = insightsEnumerable == Enumerable.Empty<Insight>()
                ? new Insight[] { } : insightsEnumerable.ToArray();

            // only fire insights generated event if we actually have insights
            if (insights.Length != 0)
            {
                OnInsightsGenerated(insights.Select(InitializeInsightFields));
            }

            ProcessInsights(insights);
```

**Comment by Martin-Molinero** [comment]
Hi @olegsheyner,

`FillModel`: If the subtype is implemented in C# it does not need access to `GetPricesCheckingPythonWrapper` since it's a work around just for Python based derivates. If the derivate is a Python implementation it should be able to directly call the base `GetPrices()` (not the `GetPricesCheckingPythonWrapper`). The use case for this method is a Python derivate implementing `GetPrices()` called by a base C# implementation, this unit test https://github.com/QuantConnect/Lean/blob/master/Tests/Common/Orders/Fills/BackwardsCompatibilityFillModelsTests.cs#L447. Let me know if it makes sense.

`Algorithm`: Interesting, I think that I understand, events like `ScheduledEvent` feature? This seems like a new missing feature of Lean, similar to the one requested at https://github.com/QuantConnect/Lean/issues/3024. Although I'm not sure about exposing the framework pipeline, and letting the user derivate algorithm implement it them selfs instead.

**Comment by mchandschuh** [comment]
Would the `EmitInsights` methods work for your use case? Here's an [example algorithm](https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/ConvertToFrameworkAlgorithm.cs#L76) that uses it. The `EmitInsights` function allows your algorithm to push insights through the framework infrastructure as if it was generated directly from an alpha model.

**Comment by olegsheyner** [comment]
@mchandschuh, thank you - `EmitInsights` method works for my use case, no further modifications necessary to `Algorithm`

@Martin-Molinero: understood re: `FillModel.GetPricesCheckingPythonWrapper`.  So as a summary, `FillModel.IsExchangeOpen` is the only one needed.  I will amend PR accordingly.

**Pull request merged**
