### PR TITLE
Fixes bug for data feeds for non-usd forex currencies

### PR DESCRIPTION
**Pull request by devalkeralia**
Fixes bug for data feeds for non-USD forex currencies for the entries added in the Symbol Properties database. Quote currency mismatch.

Solution for #453

### CODE REVIEW

**Comment by jaredbroad** [comment]
@mchandschuh @StefanoRaggi any thoughts on this fix? Is there anything missing?

E.g. GBPJPY 
-> Breaks down to USDJPY, GBPUSD
-> USDJPY adds successfully - because security currency JPY matches the cash currency JPY.
-> GPBUSD fails because "this" cash object is GBP, which doesn't match USD quote currency security symbol.

**Comment by StefanoRaggi** [comment]
For GBPJPY, shouldn't `EnsureCurrencyDataFeed` always be called on a JPY `Cash` instance (because JPY is the quote currency) ?
If this is the case, `this` or `quoteCash` objects should be the same instance and the following test is passing also before the change:

```
        [Test]
        public void EnsureInternalCurrencyDataFeedForNonUsdQuoteCurrencyDoesGetAdded()
        {
            const int quantity = 100;
            const decimal conversionRate = 1 / 100m;
            var cash = new Cash("JPY", quantity, conversionRate);
            var cashBook = new CashBook();
            cashBook.Add("JPY", cash);

            var symbol = Symbol.Create("GBPJPY", SecurityType.Forex, Market.FXCM);

            var subscriptions = new SubscriptionManager(TimeKeeper);
            var securities = new SecurityManager(TimeKeeper);
            securities.Add(symbol, new Security(SecurityExchangeHours, subscriptions.Add(symbol, Resolution.Minute, TimeZone, TimeZone), new Cash(CashBook.AccountCurrency, 0, 1m), SymbolProperties.GetDefault(CashBook.AccountCurrency)));

            cash.EnsureCurrencyDataFeed(securities, subscriptions, MarketHoursDatabase.AlwaysOpen, SymbolPropertiesDatabase.FromDataFolder(), MarketMap, cashBook);
            var config = subscriptions.Subscriptions.Single(x => x.Symbol == Symbols.USDJPY);
            Assert.IsTrue(config.IsInternalFeed);
        }

```
and it shows the internal feed has been correctly added:
`Trace:: Cash.EnsureCurrencyDataFeed(): Adding USDJPY for cash JPY currency feed
`

Does this message show in the logs for issue #453 ?

**Comment by jaredbroad** [comment]
Yes the message shows in logs, USDJPY is added successfully. I think the algorithm also needs the GBPUSD feed for the GBP cash holding (i.e. 1k GBPJPY lot = 1k long GBP, 140k short JPY). To get back to the account currency we need conversions for both.

The CashBook.EnsureCurrencyDataFeed() loops over all cash entries in book -> calling cash.EnsureCurrencyDataFeed. USD, JPY then finally "GBP" -> and exception throws when the "GBP" cash string != security GBPUSD "USD" quote currency.

Previously (before the lot size push 2 weeks ago) the default symbol properties was used - causing symbolProperties.QuoteCurrency to have the same currency as the cash.QuoteCurrency. Now we have real quote currencies in the symbol-property-database this bug has surfaced (it is easily repeatable, just run GBPJPY).

**Comment by StefanoRaggi** [comment]
Never mind, the bug fix is correct.
`EnsureCurrencyDataFeed` is called for both JPY and GBP cash objects.

Here is a test (failing now, passing after the fix), it could be added to CashTests.cs

        [Test]
        public void EnsureInternalCurrencyDataFeedsForNonUsdQuoteCurrencyGetAdded()
        {
            const int quantity = 100;
            const decimal conversionRate = 1 / 100m;
            var cashJPY = new Cash("JPY", quantity, conversionRate);
            var cashGBP = new Cash("GBP", quantity, conversionRate);
            var cashBook = new CashBook();
            cashBook.Add("JPY", cashJPY);
            cashBook.Add("GBP", cashGBP);

            var symbol = Symbol.Create("GBPJPY", SecurityType.Forex, Market.FXCM);

            var subscriptions = new SubscriptionManager(TimeKeeper);
            var securities = new SecurityManager(TimeKeeper);
            securities.Add(symbol, new Security(SecurityExchangeHours, subscriptions.Add(symbol, Resolution.Minute, TimeZone, TimeZone), new Cash(CashBook.AccountCurrency, 0, 1m), SymbolProperties.GetDefault(CashBook.AccountCurrency)));

            cashJPY.EnsureCurrencyDataFeed(securities, subscriptions, MarketHoursDatabase.AlwaysOpen, SymbolPropertiesDatabase.FromDataFolder(), MarketMap, cashBook);
            var config1 = subscriptions.Subscriptions.Single(x => x.Symbol == Symbols.USDJPY);
            Assert.IsTrue(config1.IsInternalFeed);

            cashGBP.EnsureCurrencyDataFeed(securities, subscriptions, MarketHoursDatabase.AlwaysOpen, SymbolPropertiesDatabase.FromDataFolder(), MarketMap, cashBook);
            var config2 = subscriptions.Subscriptions.Single(x => x.Symbol == Symbols.GBPUSD);
            Assert.IsTrue(config2.IsInternalFeed);
        }

**Comment by jaredbroad** [comment]
Excellent! Thank you for the feedback.

**Pull request merged**
