### PR TITLE
DockerfileLeanFoundation package updates and new additions

### LINKED ISSUE #2568: Add seaborn library
#### Expected Behavior
[seaborn](https://seaborn.pydata.org/) is whitelisted in QuantConnect.

#### Actual Behavior
[seaborn](https://seaborn.pydata.org/) is not available.

#### Potential Solution
Adds the following in [DockerfileLeanFoundation](https://github.com/QuantConnect/Lean/blob/master/DockerfileLeanFoundation#L79):
```
conda install -c anaconda seaborn
```

Testing the potential solution:
- Build the docker image with the dockerfile after the changes.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### LINKED ISSUE #4499: Library Request: PyFlux
#### Expected Behavior
Support PyFlux https://github.com/RJT1990/pyflux

#### Actual Behavior
No support for PyFlux

#### Potential Solution
Add PyFlux 
 
#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### LINKED ISSUE #4528: Library Request: Optuna
#### Expected Behavior
Support Optuna https://optuna.org/

#### Actual Behavior
No support for Optuna

#### Potential Solution
Add Optuna
```bash
conda install -c conda-forge optuna
```
#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### LINKED ISSUE #4587: Library Request: scikit-learn 0.24
#### Expected Behavior
Supports scikit-learn 0.24

#### Actual Behavior
Supports scikit-learn 0.21.3

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### LINKED ISSUE #4588: Support NLTK stopwords Library
#### Expected Behavior
Support NLTK `stopwords` Library in the foundation

#### Actual Behavior
No support for NLTK `stopwords` Library in the foundation

#### Potential Solution
Add NLTK Vader `stopwords` Library to the foundation.

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### LINKED ISSUE #4624: Library Request: findiff
#### Expected Behavior
Supports [findiff](https://github.com/maroba/findiff)

#### Actual Behavior
Does not support findiff

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### LINKED ISSUE #4627: Library Request: sktime
#### Expected Behavior
Supports [sktime](https://sktime.org/) and [sktime-dl](https://github.com/sktime/sktime-dl)

#### Actual Behavior
Does not support sktime

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### LINKED ISSUE #4629: Library Request: Hyperopt
#### Expected Behavior
Supports [Hyperopt](https://github.com/hyperopt/hyperopt)

#### Actual Behavior
Does not support Hyperopt

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### LINKED ISSUE #4651: Library Request: BayesianOptimization
#### Expected Behavior
Supports [BayesianOptimization](https://github.com/fmfn/BayesianOptimization)

#### Actual Behavior
Does not support BayesianOptimization

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### LINKED ISSUE #4746: Library Request: Rpy2
#### Expected Behavior
Support [Rpy2](https://pypi.org/project/rpy2/)
Adds R library exuber. 

#### Actual Behavior
Does not support [Rpy2](https://pypi.org/project/rpy2/)

#### Potential Solution
Review and approve [Rpy2](https://pypi.org/project/rpy2/)
```python
from rpy2.robjects.packages import importr

exuber = importr('exuber')

# params
x = np.random.rand(500) # python code, test data
adf_lag = 2
bubble = exuber.radf(x, minw= 50, lag = adf_lag)
``` 
#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### LINKED ISSUE #4782: Library Request: Pingouin
#### Expected Behavior
Support [Pingouin](https://pingouin-stats.org/)

#### Actual Behavior
Does not support [Pingouin](https://pingouin-stats.org/)

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### LINKED ISSUE #4813: Library Request: QuantEcon
#### Expected Behavior

Availability for the QuantEcon package at https://github.com/QuantEcon/QuantEcon.py. Should also allow one to fully be able to follow through their examples at https://quantecon.org/notebooks/.

#### Checklist

[x] I have completely filled out this template
[x] I have confirmed that this issue exists on the current master branch
[x] I have confirmed that this is not a duplicate issue by searching issues

### PR DESCRIPTION
**Pull request by gsalaz98**
### This PR is on top of #5036 

Package updates and new installs included in this PR:
seaborn (Closes #2568)
pyflux (Closes #4499)
optuna (Closes #4528)
sklearn (Updated, closes #4587)
ntlk.download('stopwords') (Closes #4588)
findiff (Closes #4624)
sktime (Closes #4627)
sktime-dl (Closes #4627)
hyperopt (Closes #4629)
bayesian-optimization (Closes #4651)
rpy2 (Closes #4746)
pingouin (Closes #4782)
quantecon (Closes #4813)
matplotlib (Updated)
torch-scatter, torch-sparse, torch-cluster, torch-spline-conv, torch-geometric (Partial of #4857)

Packages that are pending addition or are unable to be added at the moment:
pysde (TODO, unable to be installed)
pandas_market_calendars (TODO, review dependencies)
feature-selector (TODO, has strict package requirements)
tensorforce (TODO, requires tensorflow2)
tensorflow2 (TODO)
sagemaker (TODO)
nbeats (TODO, requires tensorflow2)
dgl (TODO, requires custom build w/ build-essentials)
stellargraph (TODO)
ruptures (TODO)
simpy (TODO)
coach (TODO, requires apt-get installs)
stable-baselines3 (TODO, might be incompatible)
modin (TODO)

#### Related Issue

Issues posted in description
#### Motivation and Context

Adds user requested packages
#### Requires Documentation Change

Yes, update package list on QC docs website
#### How Has This Been Tested?

Ran all tests, all passing

Might require some new package version tests

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [ ] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by hohoCode** [comment]
Could you please update the library: mlfinlab from 0.9.1 in lean foundation docker to the latest version 1.5.1? Thanks.

**Comment by Martin-Molinero** [comment]
Let's test live/backtesting/research with `refactor-dockerfileleanfoundation-python-pkg-updates-2-e33552f-37e65eb 10225`

**Comment by gsalaz98** [comment]
Package imports: 

```
    torch-scatter==2.0.5            \
    torch-sparse==0.6.8             \
    torch-cluster==1.5.8            \
    torch-spline-conv==1.2.0        \
    torch-geometric==1.6.3
```

are failing with the following error:

```
RuntimeError: Detected that PyTorch and torch_scatter were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_scatter has CUDA version 0.0. Please reinstall the torch_<pkg> that matches your PyTorch install.
```

**Comment by Martin-Molinero** [comment]
Rebuilt at `refactor-dockerfileleanfoundation-python-pkg-updates-2-702b111-a7d32a9 10514`

**Comment by gsalaz98** [comment]
Tested backtesting (Py/C#), backtesting debugging (Py), research (Py/C#), and live (Py/C# QC Paper and IB) - all successful

**Review by Martin-Molinero — APPROVED** [review]

**Pull request merged**
