### PR TITLE
Implement Hurst Exponent (HE) indicator

### LINKED ISSUE #3924: Adds Hurst Exponent Indicator
#### Expected Behavior
Hurst Exponent Indicator is part of Lean indicator collection.

#### Actual Behavior
Hurst Exponent Indicator is not part of Lean indicator collection.

#### Potential Solution
Implement Hurst Exponent Indicator.
Community suggestion: 
https://www.quantconnect.com/forum/discussion/1695/hurst-exponent-indicator/p1
Note: Indicator implementation **must** include unit tests with third party data.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by JosueNina**
#### Description
This pull request introduces the Hurst Exponent indicator, which measures the long-term memory or self-similarity in a time series. The indicator helps analyze the persistence or mean-reversion behavior of a time series, providing valuable insights into market trends and volatility.

#### Related Issue
Closes #3924

#### Motivation and Context
The Hurst Exponent indicator is essential for quantitative analysis as it helps identify the nature of trends in financial time series data.

#### Requires Documentation Change
Yes, the documentation should be updated to include usage instructions for the Hurst Exponent indicator

#### How Has This Been Tested?
The Hurst Exponent indicator has been tested using unit tests that verify the calculation of the indicator over historical data. This includes testing edge cases and validating the computation of standard deviation and regression line slope.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Review by Martin-Molinero — APPROVED** [review]
Thank you! 🙌

**Comment by ikamanu** [comment]
Great to see this. Thanks team!

**Comment by ikamanu** [comment]
How soon will this be available in the cloud IDE?  currently I'm getting errors when i try to reference 'self.he' : 
object has no attribute 'he' . 

I think it's just an older build  ( currently cloud IDE showing I am on this build master v16770 - 2024-12-04 22:19 )

**Comment by Martin-Molinero** [comment]
Hey @ikamanu! Will be available starting from version 16771 (eta ~40min). Cloud autocomplete might delay little more but eod/tomorrow should be there

**Comment by ikamanu** [comment]
> Hey @ikamanu! Will be available starting from version 16771 (eta ~40min). Cloud autocomplete might delay little more but eod/tomorrow should be there

Got it now. looking good. thanks!

**Pull request merged**
