### PR TITLE
Update QCAlgorithm.Indicators.cs

### PR DESCRIPTION
**Pull request by lockyssmith**
Added Keltner channels to helper method

### CODE REVIEW

**Comment by jaredbroad** [comment]
This one fails repeatably for this reason:

QCAlgorithm.Indicators.cs(489,16): error CS0246: The type or namespace name `KeltnerChannels' could not be found. Are you missing an assembly reference?
			Task "Csc" execution -- FAILED

Did it build locally?

**Comment by mchandschuh** [comment]
This change should have been applied to the existing pull request.  In this pr there is no Keltner channel implementation.  We can merge the other first and then this one and it should build, or, preferably, I can bring it down tonight and merge them together in one commit. We also need tests before this should go into master.

**Comment by mchandschuh** [comment]
I'll merge this along with the other keltner PRs into one commit on master.

**Comment by lockyssmith** [comment]
Sorry guys.  Next time I'll park it all under one pull request

**Comment by mchandschuh** [comment]
Merged in Keltner Channels in https://github.com/QuantConnect/Lean/commit/b79431a8c912f1aa23ed3fde852a2a03f490417d

**Pull request closed without merging**
