### PR TITLE
Adds DelistingEventsAlgorithm.py

### PR DESCRIPTION
**Pull request by AlexCatarino**
Adds Python version of DelistingEventsAlgorithm

### CODE REVIEW

**Comment by jaredbroad** [comment]
Thanks for the great PR's @AlexCatarino! Please fix the merge conflicts and we'll pull it in

**Comment by jaredbroad** [comment]
Nice work @AlexCatarino, please resubmit with the conflicts resolved :)

**Comment by mchandschuh** [comment]
Looks like this file didn't make it into the csproj. I'll add it.

**Comment by mchandschuh** [comment]
Merged in https://github.com/QuantConnect/Lean/commit/37c6f1eb0e30553b7016884542f90f4db434b2f3

**Pull request closed without merging**
