### PR TITLE
Issue #2820: Daily and Hour Resolution History Requests Slow

### PR DESCRIPTION
**Pull request by stan4git**
(Initial review of the new feature, more improvements to come.) 
Daily/Hour resolution history request is an order of magnitude slow than minute/second/ticks.
This change is based on the result of the performance profiling. 

#### Change Details
This PR is to address the problem where daily/hour history request is slow. After a couple of performance profiling, it shows there are a couple of performance hotpots:

1. Each history request unzips the zip file cached in ZipDataCacheProvider, which is computational expensive and unnecessary. Also, re-creating stream for each request is also contribute to the slow down.
2. There are multiple code paths isDailyOrHour also causes performance difference at scale.
3. Update the in-house cache to MemoryCache with capacity/time limit.
4. Include the benchmark algorithm to this PR
5. Flight this new feature. Based on config settings to select which cache provider to use.
6. Confirm UTC/Exchange Timezone align with history data.
7. (Todo) Unit tests
8. Provide baseline and improved performance profiles here. 
9. (Pending) Front-load data point conversion when caching (string->olchv) to avoid duplicate processing in every MoveNext(). 

#### Related Issue
https://github.com/QuantConnect/Lean/issues/2820

#### Motivation and Context
This is LEAN core engine performance improvement.

#### Requires Documentation Change
N/AP

#### How Has This Been Tested?
A new benchmark algorithm with History() in OnData().
Process profiling of each method call and timers.
Unit tests will come after.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by stan4git** [comment]
Here is a quick summary of performance test with the benchmark algo.
(Per request time unit: Ticks)

ZipFileCache Daily Avg: | 111071.7248
ZipFileCache Minute Avg: | 16564.97222

DataPointCache Daily Avg: | 2383.724771
DataPointCache Minute Avg: | 11974.46296

Daily request improvement: | 97.85%
Minute request improvement: | 27.71%

**Comment by jaredbroad** [comment]
Hey Stan, interesting PR and appreciate the deep dive into the daily data. It would be nice to streamline the stack vs building a parallel one via FetchEnumerator. Putting two methods to do similar parallel actions looks like a giant IF statement built into the interface :\ 

Please avoid all white space or non-functional personal style changes like `this.` scattered through the code. We use MS conventions for the C# base and ask people follow the styles in the surrounding code.

Perhaps there's a way to salvage the PR by placing a cache *above* the stream IDataCacheProvider. ie.
 `Normal Stack < CachingTextStreamReader (caching and decisions on creating idc) < idc.Stream`

For PR's this big we suggest working with core team in slack first to design it; to reduce the chances of the whole PR being unmergable. 

`startTimeAtExchange, endTimeAtExchange` these variable name changes would be an awesome separate isolated PR.

**Comment by stan4git** [comment]
> Hey Stan, interesting PR and appreciate the deep dive into the daily data. It would be nice to streamline the stack vs building a parallel one via FetchEnumerator. Putting two methods to do similar parallel actions looks like a giant IF statement built into the interface :\
> 
> Please avoid all white space or non-functional personal style changes like `this.` scattered through the code. We use MS conventions for the C# base and ask people follow the styles in the surrounding code.
> 
> Perhaps there's a way to salvage the PR by placing a cache _above_ the stream IDataCacheProvider. ie.
> `Normal Stack < CachingTextStreamReader (caching and decisions on creating idc) < idc.Stream`
> 
> For PR's this big we suggest working with core team in slack first to design it; to reduce the chances of the whole PR being unmergable.
> 
> `startTimeAtExchange, endTimeAtExchange` these variable name changes would be an awesome separate isolated PR.

Hey Jared,
Thanks for reviewing the change. Will join the a slack group conversation.

**I was expecting multiple iterations due to the nature of this feature and this iteration is not targeting merging**, based on the goal of this change I couldn't think of a better way to break down the change into smaller PRs. This PR was targeting:
1. History request performance hot spot research and evaluate potential solutions (along with the benchmark mechanisms)
2. Start the conversation and exchange of opinions on design, and generate followup tasks accordingly


**To address your comment:**
1. **Styling**: I agree with you and Stefano's point on consistency and that is not the major focus here. Will address in next iteration. 
(I would try another time to nag you folks off some of them in the future tho :p)
2. **Code structure**: 
  2.1. The approach here is tried to simplify benchmark comparison between old/new code by setting cache provider in config.json. **If we are happy about the DataPointCaching approach, I will clean up the code accordingly (the interface)**. See next iteration.
  2.2. I am against the streaming approach: it is causing unnecessary string chopping of each data point downstream(even for cached data) and it's hard to manage(say sort, random access, filter data points). My plan is to do the string conversion ONLY ONCE when creating the cache. It could very likely bring another 30%+ increase in overall performance.
3. Yes. Please create two tasks
- [Performance] Change line.ToCsv() to line.Split()
- [Styling] Include location in time variables (startTimeAtExchange, endTimeUtc, etc...)

**Comment by jaredbroad** [comment]
Thank you @stan4git , closing in favor of #2975

**Pull request closed without merging**
