### PR TITLE
add TradierOrderClass Oto, Oco, Otoco

### PR DESCRIPTION
**Pull request by mingwugmail**
#### Description
add TradierOrderClass Oto, Oco, Otoco

#### Related Issue
n.a.

#### Motivation and Context

https://www.quantconnect.com/forum/discussion/7791/how-to-get-the-brokerage-object-in-the-algorithm-object/p1

One example:

https://documentation.tradier.com/brokerage-api/trading/advanced-orders 

Tradier has many advanced order types, which may not be supported by other brokerages at all, hence won't be avaliable in a common Brokerage interface in the current framework.

And the user may also want to call some Tradier specfic api that are not be captured by the common Brokerage interface (which can only be the least common denominator of all the supporeted Brokerages as always when you have abstraction layer).

So expose the brokerage object directly to the Algorithm object will give user more freedom and flexibility. Most of the time, a user only use one or two brokerages, the ability to switch between all these brokages is not a big concern. And the user is more concerned about the ability to call vendor specific api of their already selected brokerage.
https://github.com/QuantConnect/Lean/tree/master/Brokerages

 

#### Requires Documentation Change
Not yet.

#### Types of changes
- [x] New feature (non-breaking change which adds functionality)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by mingwugmail** [comment]
@jaredbroad

1st step:

https://www.quantconnect.com/forum/discussion/7791/how-to-get-the-brokerage-object-in-the-algorithm-object/p1

**Comment by jaredbroad** [comment]
Hi to prevent incomplete code please develop on a branch and get a complete working live trading tested integration before opening a pull-request to master

**Comment by mingwugmail** [comment]
I think it's much harder to review a PR of 1000 lines code instead of 10 lines.

Also from my side, I work on this at spare time, it's hard to prepare a big PR of 1000 lines of code at once. I can work on it piece by piece at small (& relatively in-dependent) steps. Otherwise, it will either take too long, or I need frequently merge if other people working on the same file.

**Comment by mingwugmail** [comment]
Hi @jaredbroad, I'd like to discuss first before I make further change, since this could be a big change. 

My 1st question:

https://github.com/QuantConnect/Lean/blob/master/Common/Orders/SubmitOrderRequest.cs#L104

Is SubmitOrderRequest the only object that the Algorithm can create any type of order? i.e. the order entry point?

Thanks.

**Pull request closed without merging**
