### PR TITLE
Do not send internal SecurityChanges to Algorithm

### PR DESCRIPTION
**Pull request by Martin-Molinero**
#### Description

- Will not send internal security changes to the Algorithm by default.
  Following custom security changes filter pattern. Updating regression
  algorithms to assert behavior.
- The universe member will know whether it was added with internal
  configurations or not

#### Related Issue

N/A
#### Motivation and Context

User experience
#### Requires Documentation Change

N/A
#### How Has This Been Tested?

Algorithm reproducing the issue
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Review by jaredbroad — APPROVED** [review]

**Comment by JakeTheSnake3p0** [comment]
This update broke my script that allows me to run the algorithm from within the research environment.

```python
from QuantConnect.Data.UniverseSelection import SecurityChanges
from QuantConnect.Research import QuantBook

class Research:
    def __new__(self, **config):
        base = config["algorithm"]

        class ResearchAlgorithm(base):

            # Hold a reference to a QuantBook for later use and explicitly run initializers
            def __init__(self):
                self.qb = QuantBook()
                self.qb.SetTimeZone(self.TimeZoneLocale)
                self.ObjectStore = self.qb.ObjectStore
                super().__init__()
                super().Initialize(**config)

            # Since universes aren't working in the research notebook,
            # add the securities within this method
            def SetSecurities(self):
                super().SetSecurities()

                for symbol in self.config["symbols"]:
                    security = self.qb.AddEquity(
                        symbol, self.UniverseSettings.Resolution
                    )
                    self.Securities[str(security)] = security

                # This is the offending line ------------
                changes = SecurityChanges.Added(self.Securities.Values)
                self.OnSecuritiesChanged(changes)
                self.Alpha.OnSecuritiesChanged(self, changes)
            
            def History(self, *args, **kwargs):
                return self.qb.History(
                    args[0],
                    self.StartDate,
                    self.EndDate,
                    args[2],
                    **kwargs,
                )

            def GetFundamental(self, *args, **kwargs):
                return self.qb.GetFundamental(*args, **kwargs)

            def AddOption(self, *args, **kwargs):
                return self.qb.AddOption(*args, **kwargs)

        return type(f"{base.__name__}Research", (ResearchAlgorithm,), {})()
```

I've been developing locally for some time, but after pushing to the cloud and running my notebook, I get the error:

> AttributeError: type object 'SecurityChanges' has no attribute 'Added'

I changed it to `AddedSecurities` instead, but it then said it needs to be an instance. Can you please let me know how to account for this change? Does the quantbook instance have SecurityChanges somewhere I can access?

**Comment by Martin-Molinero** [comment]
Hey @JakeTheSnake3p0! Sorry about that, I think something like `SecurityChanges.Create(self.Securities.Values, [], [], [])` would do the trick for you

**Comment by JakeTheSnake3p0** [comment]
I tried it but received the following error:

> TypeError: No method matches given arguments for Create: (<class 'list'>, <class 'list'>, <class 'list'>, <class 'list'>)

I even tried the most basic instantiation of all empty lists but the same error showed.

**Comment by Martin-Molinero** [comment]
Hey @JakeTheSnake3p0! you are right, believe this is a bug in pythonNet, https://github.com/QuantConnect/pythonnet/pull/63 should fix it, we will address it shortly

**Comment by JakeTheSnake3p0** [comment]
I tried updating lean (`pip install --upgrade lean`) but it didn't seem to download anything new; the error persists. I'm not sure how version updates work with this repo.

**Comment by Martin-Molinero** [comment]
Hey @JakeTheSnake3p0! you need to update your local lean image, `docker pull quantconnect/lean:latest` should do the trick for you

**Comment by JakeTheSnake3p0** [comment]
Thanks @Martin-Molinero , that fixed it! I was using `quantconnect/research:latest` and relying on lean-cli to auto-update it for me as it had done so in the past.

**Pull request merged**
