### PR TITLE
Refactored AlgoSeekFuturesConverter.cs to remove reduntant code

### PR DESCRIPTION
**Pull request by prasadsom**
I was going to suggest improvement on PR https://github.com/QuantConnect/Lean/pull/3789 , but it was merged before I'd chance to comment. So this PR is just improvement.

#### Description
Used information present in class member `_remote` and removed redundant function(and call)

#### Related Issue
#3795 #3788 
#### Motivation and Context
Unnecessary launch of process and reading output from process object, when information can be found using member variable

#### Requires Documentation Change
NA
#### How Has This Been Tested?
NA
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by Martin-Molinero** [comment]
Hi @prasadsom,
Thanks for the PR, welcome to Lean 🎉 
In my original review to PR https://github.com/QuantConnect/Lean/pull/3789 I noted the same, but @Jay-Jay-D clarified that this is required to support a remote filesystem technology for which `EnumerateFiles` failed. I removed my comment but I probably should have added this explanation. 
@Jay-Jay-D can reconfirm here but I believe we need current implementation

**Comment by prasadsom** [comment]
Oh, I guessed there should be some explanation for existing implementation. 

> but @Jay-Jay-D clarified that this is required to support a remote filesystem technology for which EnumerateFiles failed

Are we talking about only network share here ? May be failure message there may throw some light.

**Comment by Jay-Jay-D** [comment]
Hi @prasadsom welcome to Lean!

As you guessed, there is a reason for this implementation. You can check the file's history; the original implementation enumerated files.

The actual implementation is the only one that shows consistent behavior in our production systems, and it is used everyday.

**Comment by Martin-Molinero** [comment]
Thanks, closing this issue for now

**Pull request closed without merging**
