### PR TITLE
Increase Visual Studio Plugin's Max Supported Version To Include Visual Studio 2019

### LINKED ISSUE #3143: Build-Test Visual Studio Plugin for 2019
#### Expected Behavior
The plugin installs in VS2019 

#### Actual Behavior
The plugin doesn't install.

#### Potential Solution
Review and fix arising bugs

#### Reproducing the Problem
Try and install into VS 2019.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by gsalaz98**
#### Description

Includes Visual Studio 2019 in supported versions (in `source.extension.vsixmanifest`), allowing the plugin installer to detect and allow installs for VS2019.
#### Related Issue

Fixes #3143 
#### Motivation and Context

To allow for use of the QuantConnect Visual Studio plugin for Visual Studio 2019
#### Requires Documentation Change

https://www.quantconnect.com/tutorials/open-source/backtesting-from-visual-studio - should be updated to include VS2019
#### How Has This Been Tested?

Local testing by saving and backtesting from VS2017 and VS2019 Preview
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by jaredbroad** [comment]
Will need new binaries compiled in VS2019 for deployment

**Comment by danielleiszen** [comment]
Thanks for the fast response time, however it does not work for me. I've just installed VS 2019 with .NET, Python development and VS extension development support.  I pulled the latest source from master and restored all nuget packages, then I built the VisualStudio17Plugin project. After that I installed the VSIX file from bin/Debug. It was flawless however, when I open Tools/Options/QuantConnect/Settings I see an empty panel. What did I miss? Thank you.

**Comment by Martin-Molinero** [comment]
Hi @danielleiszen ! Have you see the documentation at https://www.quantconnect.com/tutorials/open-source/backtesting-from-visual-studio ? It provides details on how the extension is used and its features.

**Comment by danielleiszen** [comment]
@Martin-Molinero thank you for your answer. In this case all fine, I can confirm that the Login feature works on VS 2019.

**Pull request merged**
