### PR TITLE
Fix wrong market hours for Oanda DE30EUR CFD

### PR DESCRIPTION
**Pull request by szymanskilukasz**
#### Description

Currently on QuantConnect Platform, Oanda CFD DE30EUR, have trading hours Mon - Fri 08:00*-22:00, when it should be Mon - Fri 01:15*-22:00 according to Oanda Trading Times https://www.oanda.com/rw-en/trading/hours-of-operation/

#### Related Issue

https://github.com/QuantConnect/Lean/issues/5538

#### Motivation and Context

Currently it's not possible to backtest, and live trade on Oanda CFD DE30_EUR Instrument because of lack of coverage of whole market trading times
#### Requires Documentation Change

Changes in documentation not required

#### How Has This Been Tested?

Not tested

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes.  (Not applicable, change only in json file)
- [ ] All new and existing tests passed. (Not sure how to run tests locally, didn't find any informations about it in the repo) 
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by szymanskilukasz** [comment]
4 tests Failed: 2x timeouts and 2x actually related to the change. 

I think expected 14 should be changed to 21 here - from 1:15 to 22:00 there are only 21 full hours 
https://github.com/QuantConnect/Lean/blob/fe2ac131af2d0614494e5c970a57d4b7c89d5f88/Tests/Engine/DataFeeds/LiveTradingDataFeedTests.cs#L1422

However I am not sure about second failed test, it seems that instead of expected 14 Ticks received 20 Ticks, but I don't understand why we should expect 14 Ticks during one day anyway. I can change it in code, but it would be better to understand this specific Tick test usecase 

https://github.com/QuantConnect/Lean/blob/fe2ac131af2d0614494e5c970a57d4b7c89d5f88/Tests/Engine/DataFeeds/LiveTradingDataFeedTests.cs#L1424

Thanks for any hints!

**Review by Martin-Molinero — APPROVED** [review]
Looks good!
You are right about the required changes in the unit tests 👍 
Expected ticks should also be 21 because time is advanced with 1 hour resolution see https://github.com/QuantConnect/Lean/blob/master/Tests/Engine/DataFeeds/LiveTradingDataFeedTests.cs#L1681 , was 20 in travis due to race condition
image

**Comment by szymanskilukasz** [comment]
@Martin-Molinero Thank you! How can I know when change was deployed to the production?

**Comment by Martin-Molinero** [comment]
> 
> 
> @Martin-Molinero Thank you! How can I know when change was deployed to the production?

Thank you! It's in production 👍 Lean v11672

**Comment by szymanskilukasz** [comment]
@Martin-Molinero I'm afraid it's still not working as intended. Both during backtest and live trading market hours for Oanda DE30EUR are 8:00 - 22:00 instead 01:15 - 22:00 as mentioned here https://github.com/QuantConnect/Lean/issues/5538

Will check are there any other places that needs to be changed, but if you have any ideas what else is missing please let me know :)

**Pull request merged**
