### PR TITLE
#96-Parameterization

### PR DESCRIPTION
**Pull request by Vincent-Chin**
Unit tests done.  Note that the Engine.cs I've included is modified with rudimentary brute-forcing logic.  It doesn't work though (hangs on initializing the second iteration.)  I also never got around to parallelizing the loop with Parallel.ForEach.

### CODE REVIEW

**Comment by Vincent-Chin** [comment]
LoadParameters.cs in Tests is an extraneous file.  Didn't notice it during the commit.

**Comment by jaredbroad** [comment]
This is a great first step @Vincent-Chin! There's some changes we'll need to make to properly use it in LEAN though. If you're open to making them we can merge in the PR.

1. The configuration parameter set must come through the Job packet, and, 
2. The job would have 1-set of parameters.
3. Revert Engine.cs & replace it will a simple way of setting parameters from the job packet.

This way LEAN is still a singular instance, running a configured parameter set. 

3. Later, we'll make the GUI spin up hundreds of LEAN instance objects each with different job packets specifying their configuration permutation.

**Comment by mchandschuh** [comment]
I think it would also be beneficial to separate the concept of the parameter from the concept of the search method. For example, int parameter defines a min/max/step property. While the min/max do define the parameter, the step defines how we will search the parameter space. This is a concern best saved for optimization, so as part of this PR let's remove the Step properties.

**Comment by jaredbroad** [comment]
Thanks for the PR @Vincent-Chin ! This is an awesome start but we'd like to design Parameterization with a more holistic approach in mind where parameters are passed through the jobs system, and its well integrated with the Engine class.

Lets keep this on reference and come back to it later once we start that project!

**Pull request closed without merging**
