### PR TITLE
Super Trend Indicator

### LINKED ISSUE #4653: Indicator Request: Supertrend
#### Expected Behavior

Supertrend indicator request. [Thread](https://www.quantconnect.com/forum/discussion/9072/hekin-ashi-amp-supertrend-indicator-in-python/p1).
#### Actual Behavior

Indicator not yet supported.
#### Checklist

- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### PR DESCRIPTION
**Pull request by jovuribe**
#### Description

Creates super trend indicator. Modifies code put forth by IlshatGaripov pull request #5209

The super trend indicator uses ATR and upper/lower bands to determine trends.

#### Related Issue

Closes #4653
https://github.com/QuantConnect/Lean/issues/4653#issue-685636982

#### Requires Documentation Change

Yes

#### How Has This Been Tested?

Downloaded a spreadsheet containing formulas for the super trend indicator. SPY OHLC data from TradingView were used as inputs. Wrote test cases to check SuperTrend values against each other. 

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by IlshatGaripov** [comment]
we now have a strategy in production at super trend. I started doing tests but my indicator outputs turned out to differ a bit from tradingview's. may I clarify the data given here are taken from the trading view? you got a complete match @jovuribe ?

**Comment by jovuribe** [comment]
@IlshatGaripov here is the website I used to get the super trend values: https://tradingtuitions.com/supertrend-indicator-excel-sheet-with-realtime-buy-sell-signals/. The reason why I didn't use TradingView was because it was unclear how they calculated it. What moving average type was used for the ATR, etc,? I plugged SPY values into the spreadsheet and used that.

**Comment by jovuribe** [comment]
Switched the test data to DWAC because variables such as _currentTrailingLowerBand are unknown in the SPY dataset. With a newly ipo'd security, ATR and _currentTrailingLowerBand are NA which fit the TradingView code logic.

**Comment by ikamanu** [comment]
It's been a little while... any update here?

**Comment by ikamanu** [comment]
Any updates here?

**Review by Martin-Molinero — APPROVED** [review]
Nice! Sorry for the delayed review 🚀

**Comment by ikamanu** [comment]
Thank you!

**Pull request merged**
