### PR TITLE
Added the day of mourning for former president George H.W. Bush

### PR DESCRIPTION
**Pull request by RohanTalip**
#### Description

Added the day of mourning for former president George H.W. Bush:
https://www.sec.gov/oit/announcement/edgar-be-closed-wednesday-december-5-2018

Added more context in the comment for 2007-01-02 (the day of mourning for former president Gerald R. Ford) and fixed the typo.

Rearranged the specific, non-recurring dates above the recurring dates.

#### Related Issue

Fixes issue #3920 

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by RohanTalip** [comment]
> I think this also requires a similar update to the [`market-hours-database.json`](https://github.com/QuantConnect/Lean/blob/master/Data/market-hours/market-hours-database.json) file.

"12/05/2018" is already in the market-hours-database.json file:
https://github.com/QuantConnect/Lean/blob/master/Data/market-hours/market-hours-database.json#L23156

These are the errors from the Travis CI run:
```
Errors and Failures:
1) Test Failure : QuantConnect.Tests.Common.Securities.Futures.FuturesExpiryFunctionsTests.EnergiesExpiryDateFunction_WithDifferentDates_ShouldFollowContract("EH","00:00:00")
     Failed for symbol: EH
  Expected: 2018-12-05 00:00:00.000
  But was:  2018-12-06 00:00:00.000
at QuantConnect.Tests.Common.Securities.Futures.FuturesExpiryFunctionsTests.EnergiesExpiryDateFunction_WithDifferentDates_ShouldFollowContract (System.String symbol, System.String dayTime) [0x000a0] in <986589aec6fc4f87baa1c0adc6be54f8>:0
2) Test Failure : QuantConnect.Tests.Common.Securities.Futures.FuturesExpiryFunctionsTests.MeatsExpiryDateFunction_WithDifferentDates_ShouldFollowContract("HE","12:00:00")
     Failed for symbol: HE
  Expected: 2018-12-14 12:00:00.000
  But was:  2018-12-17 12:00:00.000
at QuantConnect.Tests.Common.Securities.Futures.FuturesExpiryFunctionsTests.MeatsExpiryDateFunction_WithDifferentDates_ShouldFollowContract (System.String symbol, System.String dayTime) [0x000a0] in <986589aec6fc4f87baa1c0adc6be54f8>:0
```

This appears to be happening because FuturesExpiryUtilityFunctions#AddBusinessDays() and FuturesExpiryUtilityFunctions#NthLastBusinessDay() use the  FuturesExpiryUtilityFunctions#NotHoliday() static method, which uses the USHoliday.Dates HashSet, however the actual/real futures expiration doesn't appear to have taken the day of mourning (and US holiday) into account.

Any suggestions?  Maybe futures expiration dates only take into account annually recurring holidays and not ad hoc holidays?  Should the USHoliday.Dates HashSet be split into something like USHoliday.RecurringDates and USHoliday.AdHocDates, and then recombined into USHoliday.Dates?  i.e. So that the futures expiration static methods can use USHoliday.RecurringDates?

**Comment by Jay-Jay-D** [comment]
Hi @RohanTalip , thanks for the PR.

As @mchandschuh pointed it out, the correct way to add a market close is by updating the market hours DB.

>"12/05/2018" is already in the market-hours-database.json file:
https://github.com/QuantConnect/Lean/blob/master/Data/market-hours/market-hours-database.json#L23156
Please note that `12/05/2018` is in the MHDB but **only for equities and options, not for futures**.

Given that different futures trades in different exchanges, each holiday should be added to all affected futures entries.

Respect to the ` FuturesExpiryUtilityFunctions`, [from here](https://github.com/QuantConnect/Lean/blob/8af7297578d06ea44bb45b9048002951b8218816/Common/Securities/Future/FuturesExpiryFunctions.cs#L1548), you can see that holidays are read from the MHDB first, then those dates are used in the `NthBusinessDay` method along with the `USHoliday.Dates` HashSet.

**Comment by RohanTalip** [comment]
> Please note that `12/05/2018` is in the MHDB but **only for equities and options, not for futures**.

Ah, OK, thanks.


> Respect to the ` FuturesExpiryUtilityFunctions`, [from here](https://github.com/QuantConnect/Lean/blob/8af7297578d06ea44bb45b9048002951b8218816/Common/Securities/Future/FuturesExpiryFunctions.cs#L1548), you can see that holidays are read from the MHDB first, then those dates are used in the `NthBusinessDay` method along with the `USHoliday.Dates` HashSet.

Thanks, however, from looking at symbol /HE (Lean Hog Futures) in ThinkOrSwim, I see that the HE futures symbol traded normally on 2018-12-05.  i.e. It did not appear to be a holiday for that symbol.

I'm not able to look up the charts for symbol EH (Ethanol) in ThinkOrSwim.  tradingview.com shows it [trading](https://s.tradingview.com/cmewidgetembed/?frameElementId=tradingview_7a535&symbol=CBOT_GBX%3AZHF2019&interval=D&hidesidetoolbar=0&symboledit=0&saveimage=1&toolbarbg=E4E8EB&studies=%5B%5D&style=0&studies_overrides=%7B%7D&overrides=%7B%7D&enabled_features=%5B%5D&disabled_features=%5B%5D&venue=1&utm_source=www.cmegroup.com&utm_medium=widget&utm_campaign=chart&utm_term=CBOT_GBX%3AZHF2020) on 2018-12-05, albeit at a lower volume, so that's not really conclusive.

When I looked at a small and random sampling of futures in ThinkOrSwim, it seemed that most (except for /ES and /NQ) were open for trading on 2018-12-05.  Please let me know if there is a free online resource for charting futures, showing the market hours for each day.

In any case, if a future was open for trading on 2018-12-05 and that is accurately reflected in market-hours-database.json there's still an issue of the `USHoliday.Dates` HashSet being incorrectly used (with 2018-12-05 present in the HashSet), since those US holiday dates will not (in general) reflect the holiday dates for that future.  You can follow this logic with symbol HE and 2018-12-05, as an example.

That's why I was suggesting splitting the `USHoliday.Dates` HashSet above into recurring dates and ad hoc dates.  (I suspect the expiration dates for futures are set way in advance, using just recurring holidays, and that these are not adjusted when there's an impromptu / ad hoc holiday declared.)

I can look into making such a change a bit later.

**Comment by Jay-Jay-D** [comment]
> When I looked at a small and random sampling of futures in ThinkOrSwim, it seemed that most (except for /ES and /NQ) were open for trading on 2018-12-05. Please let me know if there is a free online resource for charting futures, showing the market hours for each day.

Have you tried with CME Group page? [Here are](https://www.cmegroup.com/trading-hours.html#energy) some market hours data, but I don't think historical holidays are included. 

> In any case, if a future was open for trading on 2018-12-05 and that is accurately reflected in market-hours-database.json there's still an issue of the USHoliday.Dates HashSet being incorrectly used (with 2018-12-05 present in the HashSet)
2018-12-05 **should not** be present in the `USHoliday.Dates` HashSet

**Comment by RohanTalip** [comment]
> 2018-12-05 **should not** be present in the `USHoliday.Dates` HashSet

OK, I'll withdraw this pull request.  @Jay-Jay-D, is issue #3920 still valid then?

Should the other ad hoc / specific dates (e.g. for 9/11 (i.e. the World Trade Center attacks), Hurricane Sandy, and the other 2 days of mourning for former presidents) also be removed from the `USHoliday.Dates` HashSet?

**Comment by RohanTalip** [comment]
> Have you tried with CME Group page? [Here are](https://www.cmegroup.com/trading-hours.html#energy) some market hours data, but I don't think historical holidays are included.

Thanks, I had seen related pages, but I also wasn't able to see historical holidays.

**Pull request closed without merging**
