### PR TITLE
Updated for missing and malformed XML Comments

### PR DESCRIPTION
**Pull request by bizcad**
I only updated missing XML comments so there would be less compile warnings. In some cases I changed a /* Comment */ type comment to a 
///<summary
/// Comment
///</summary>
moving the comment into the summary

### CODE REVIEW

**Comment by mchandschuh** [comment]
Hey Nick, I love the drive to lower the compile warnings count, however, some of these comments are empty. Can we fill them in with something descriptive?  In some cases you may be able to steal the comments from the base class/interface. ([ReSharper](https://www.jetbrains.com/resharper/) has a nifty copy comments from base class quick fix)

**Comment by bizcad** [comment]
Michael,

I used ReSharper and the fill in from base class and agree it  is nifty.  Resharper is also helpful at finding the uncommented xml.  Some of the <summary>s I left empty because they were obvious, like OnData or a property that has a very descriptive name.  However some others, I did not know what they do.  I realize that the /// xml comments help with generating documentation and telesence.  So that it is important to get them all in.  

I also had some newbie issues with getting the pull request, origin and upstream to work on my fork.  It took me three times through the process to get it, but I think I have it now. I would prefer that you merge my PR so you can compile tomorrow.  None of my changes will affect the build.  Then I will then sync my fork with the upstream and work from there.  I am scared of losing the changes I have made after having gone through the process 3 times.

**Comment by bizcad** [comment]
Michael,

I have filled in the empty comments on my local repo and synced it with my github repo.  I am unsure about how to send the changes.  That is I do not know how to update the current PR.  If you merge, I can sync with the upstream and do another PR for the changes tomorrow.

Nick

**Comment by mchandschuh** [comment]
Nick it looks like you've added an extra commit to this pull request unintentionally (65eabca). When submitted pull requests it points to your entire branch. In this case, your master branch, so as you continued developing with the WMA indicator and tests, they inadvertently got added to this pull request. I'd recommend some light reading on [git branches](https://www.atlassian.com/git/tutorials/using-branches/git-branch).  Ideally, any work performed that you'd like to contribute back to the open source project would be done on its own branch so that it doesn't interfere with your personal work.

**Comment by bizcad** [comment]
Michael,
Will do.  Unintentionally is right. It is just a newbie error, and I apologize.  I just cannot seem to figure out how to do personal work and not affect the upstream until I get all my bugs ironed out and do an official pull request.  

Since you have another pull request to fix the warnings, it might be just as well to kill this pull request.  Do you have a write up on your contributor's work flow?

**Comment by mchandschuh** [comment]
I'll write up a contributor workflow today, outlining the preferred steps to take.  I'm going to close this one as @ammachado's PR covers many of the same issues anyway. As always, we appreciate the contributions!  Check back soon for the contributor's workflow to be located in the root of the QuantConnect/Lean repository.

**Comment by mchandschuh** [comment]
Nicholas,

I've gone ahead and committed a first stab at a contributor's workflow.

https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md

I think the key takeaway here is to work on branches.  They can be scary at
first but at really nice what you get the hang of them.  They help to keep
work separated.

Check it out and let me know what you think.  I gave it the quick dry run.
Let me know if you need any help.


-Michael

**Comment by bizcad** [comment]
Michael,  

I really appreciate your doing that write up. I just took a quick peek and it looks pretty good.  I will start from scratch tomorrow and add my WMA Indicator code and let you know how it went tomorrow.  

-Nick

**Pull request closed without merging**
