### PR TITLE
Feature 5108 - move to debugpy

### PR DESCRIPTION
**Pull request by marcograss**
Implements #5108 : Switch from PTVSD to DebugPy.
#### Description

PTVSD has been deprecated, debugpy is the new official python debugger for vscode/vs

#### Related Issue

#5108 

#### Motivation and Context

PTVSD will not be supported anymore, and the github project has been archived already.

#### Requires Documentation Change

The readme and relevant mentions to PTVSD have been updated to reflect the switch to debugpy.

#### How Has This Been Tested?

The tests were run in the CI before merge.
The changes have been tested locally in a windows 10 environment with Python 3.8.6 by debugging a Python Algorithm on Visual Studio Code.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by Martin-Molinero** [comment]
Hey @marcograss!
Thanks for the contribution. Believe we hadn't pushed this before because at the time debugging a docker container wasn't working correctly. Before updating we should confirm the following supported cases are still operational:
- Visual Studio Code, Visual Studio
- Debugging locally and debugging a docker container

Does it sounds right @C-SELLERS? 😁

**Comment by marcograss** [comment]
> Hey @marcograss!
> Thanks for the contribution. Believe we hadn't pushed this before because at the time debugging a docker container wasn't working correctly. Before updating we should confirm the following supported cases are still operational:
> 
> * Visual Studio Code, Visual Studio
> * Debugging locally and debugging a docker container
> 
> Does it sounds right @C-SELLERS? 😁

the issue might be related (just a guess) to the fact that with debugpy you need to specify the python interpreter (which I do here `debugpy.configure(python=shutil.which('python'))` )  . it seems to use the current executable by default, which in our case is the mono interpeter (python.net is embedded)

However I don't have a suitable environment to build the docker myself, it seems the windows build, when pushed in the quantconnect/lean docker container when building, has some problems to find the python library due to differences between windows (at least my env) and the one inside the docker with conda

**Comment by Martin-Molinero** [comment]
> the issue might be related (just a guess) to the fact that with debugpy you need to specify the python interpreter (which I do here debugpy.configure(python=shutil.which('python')) ) . it seems to use the current executable by default, which in our case is the mono interpeter (python.net is embedded)


Ah that might of been it! 👍 

> However I don't have a suitable environment to build the docker myself, it seems the windows build, when pushed in the quantconnect/lean docker container when building, has some problems to find the python library due to differences between windows (at least my env) and the one inside the docker with conda

When building cross-platform, for example windows for Linux, you have to specify the build parameter `ForceLinuxBuild` set to `true` so that it picks up the correct pythonNet binary

**Comment by C-SELLERS** [comment]
Yeah after testing today with this branch on DebugPy it seems that docker is failing to connect at all as well as some issues with local debugging. Here are my findings on testing it out.

image


I also tested PTVSD to confirm current behavior for the record

 
image

Now I recall why we didn't include this debugging method in the `./vs/readme.md`

**Comment by Martin-Molinero** [comment]
Hey!
Will close PR for now until the cases posted by @C-SELLERS are working with `debugpy`

**Pull request closed without merging**
