### PR TITLE
FxcmBrokerage.ConvertSymbol exception with CFD symbols

### PR DESCRIPTION
**Pull request by StefanoRaggi**
The Fxcm brokerage implementation during logon receives all symbols (Forex and CFD) so this bug caused a timeout in the Connect method.

### CODE REVIEW

**Comment by mchandschuh** [comment]
Thanks for the fix! I've also added a helper method to reduce the switches on security types when creating `Symbol` instances. Have a peek at [this](https://github.com/QuantConnect/Lean/blob/master/Common/Symbol.cs#L44)

**Comment by mchandschuh** [comment]
Merged in https://github.com/QuantConnect/Lean/commit/5e649baf70b3e744485ae3cf1e171f37d8154a50

**Comment by StefanoRaggi** [comment]
@mchandschuh I used the Symbol.Create() method extensively in the new ISymbolMapper branch. I'll clean up brokerages and downloaders there.

**Comment by mchandschuh** [comment]
@StefanoRaggi - you're always on top of it all! Awesome stuff. Yes, I think the Symbol.Create can cover most security types, may need overloads for creating options/futures due to needing to know extra info (expiry, strike, p/c,ect...)

**Pull request closed without merging**
