### PR TITLE
fix incorrect Kraken and Coinbase Pro fee values

### PR DESCRIPTION
**Pull request by anuj-mitul-patel**
#### Description

correct inaccurate fee values for Kraken and update fee values for Coinbase Pro

#### Related Issue

N/A

#### Motivation and Context

fixes incorrect fee values

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

N/A

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Review by Martin-Molinero — APPROVED** [review]
Thank you @anuj-mitul-patel!

**Comment by Martin-Molinero** [comment]
Think will require updating a couple of unit test that started failing see https://github.com/QuantConnect/Lean/runs/4299757976?check_suite_focus=true `ZeroNonAccountCurrency_GetMaximumOrderQuantityForTargetValue("EUR")` and `ZeroNonAccountCurrency_GetMaximumOrderQuantityForTargetValue("ARG")` (can ignore `ConsumeRequestsAdditionalTimeAfterOneMinute` he fails sometimes)

**Comment by anuj-mitul-patel** [comment]
Latest commit updates the expected values in CashBuyingPowerModelTests.cs and changes the time to after the new fees came into effect.

**Review by Martin-Molinero — APPROVED** [review]
Thanks!

**Comment by jaredbroad** [comment]
Welcome to LEAN  @anuj-mitul-patel!

**Pull request merged**
