### PR TITLE
Implements SuperTrend indicator.

### LINKED ISSUE #4653: Indicator Request: Supertrend
#### Expected Behavior

Supertrend indicator request. [Thread](https://www.quantconnect.com/forum/discussion/9072/hekin-ashi-amp-supertrend-indicator-in-python/p1).
#### Actual Behavior

Indicator not yet supported.
#### Checklist

- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### PR DESCRIPTION
**Pull request by IlshatGaripov**
#### Description
PR adds SuperTrend indicator. 

#### Related Issue
Closes #4653

#### Motivation and Context
By request of community

#### Requires Documentation Change
NA

#### How Has This Been Tested?
To be covered by tests. Would very appreciate help in obtaining the data set for tests. How do you usually collect such data?

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x ] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [ x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by jaredbroad** [comment]
Thank you for the PR @IlshatGaripov -- please see this example PR for a complete indicator PR; we need external data validation; an and API accessor method. https://github.com/QuantConnect/Lean/pull/5002/files

**Review by jaredbroad — CHANGES_REQUESTED** [review]
Updates to include header, api accessor, and tests

**Comment by IlshatGaripov** [comment]
This still requires tests, will implement it additionally, thanks,

**Comment by itsbalamurali** [comment]
@IlshatGaripov can I also request few more missing Indicators? Whole list is here to choose from: https://school.stockcharts.com/doku.php?id=technical_indicators

How about StoRsi ? ;)

Thanks for this PR.

**Comment by Martin-Molinero** [comment]
> 
> 
> This still requires tests, will implement it additionally, thanks,

Hey @IlshatGaripov! Any update on those required tests? thanks

**Comment by jaredbroad** [comment]
Closing pending tests.

**Comment by IlshatGaripov** [comment]
> @IlshatGaripov can I also request few more missing Indicators? Whole list is here to choose from: https://school.stockcharts.com/doku.php?id=technical_indicators
> 
> How about StoRsi ? ;)
> 
> Thanks for this PR.

Hey @itsbalamurali glad it was helpful, StochRsi looks interesting, let me investigate it little closer. Would def be happy to do more indicators if time was not an issue. @jaredbroad @Martin-Molinero sorry will resubmit with tests.

**Comment by movy** [comment]
@IlshatGaripov , did you manage to implement supertrend with Lean?

**Comment by IlshatGaripov** [comment]
> @IlshatGaripov , did you manage to implement supertrend with Lean?

Hey @movy yes I did manage to implement supertrend with Lean. Yet it has not been merged because PR is missing tests. You'd like to use it with QuantConnect web platform, is it correct? What is your programming language - python of C#?

**Comment by movy** [comment]
@IlshatGaripov , Python most likely, as Python code is easier to port between different algo-trading / testing frameworks.

**Pull request closed without merging**
