### PR TITLE
Merge pull request #1 from QuantConnect/master

### PR DESCRIPTION
**Pull request by ChrisFagan**
Update from Original

### CODE REVIEW

**Comment by ChrisFagan** [comment]
Hmm. I did not intend to request my changes go into QuantConnect/Lean (master). What I want is to update my branch chrisFagan/Lean with QuantConnect/Lean(master) changes since Oct2016.
If this request makes it to the QC code manager, please delete the request. 
Sorry, Chris

**Comment by ChrisFagan** [comment]
Hmm. I did not intend to request my changes go into QuantConnect/Lean (master). What I want is to update my branch chrisFagan/Lean with QuantConnect/Lean(master) changes since Oct2016.
If this request makes it to the QC code manager, please delete the request.
Sorry, Chris

**Comment by StefanoRaggi** [comment]
@ChrisFagan 
I update my master branch from Lean master almost every day, using the following command:

`git pull --rebase upstream master`

**Comment by ChrisFagan** [comment]
Thx

**Pull request closed without merging**
