### PR TITLE
feature-5181-set x64 as default build configuration for all projects on c# solution

### PR DESCRIPTION
**Pull request by TightLinesOfCode**
#### Description
Added the x64 solution configuration and also adjusted each project to have x64 for build.
Removed the ANYCPU configuration from solution to enhance consistency for users downloading the software

#### Related Issue
https://github.com/QuantConnect/Lean/issues/5181

#### Motivation and Context
Solves out of memory issues related to massively parallel downloads and lean data writer.   Also enhances the speed of the overall application by using a 64 bit address space

#### Requires Documentation Change
None

#### How Has This Been Tested?
-Built Solution with Debug and Release and verified output folders to be the same.
-Ran the default Lean Launcher project with no errors in Debug and Release mode.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [X] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [X] My code follows the code style of this project.
- [X] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [NA] I have added tests to cover my changes. 
- [no] All new and existing tests passed.    ( Default lean repository does not pass all of the unit tests )
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by Martin-Molinero** [comment]
Hey @TightLinesOfCode! Thanks for the PR, interesting
> Solves out of memory issues related to massively parallel downloads and lean data writer. Also enhances the speed of the overall application by using a 64 bit address space

Mind expanding **why**, references are welcome and believe we should also test the statements somehow.
I don't think there is a performance difference really. Compiled code should be the same. See https://stackoverflow.com/questions/11062028/performance-of-a-c-sharp-application-built-on-anycpu-vs-x64-platform-on-a-64-bit/11062102#11062102 or https://stackoverflow.com/questions/516730/what-does-the-visual-studio-any-cpu-target-mean/516740#516740 or https://medium.com/@trapdoorlabs/c-target-platforms-x64-vs-x86-vs-anycpu-5f0c3be6c9e2

Thanks to the PR, I'm realizing though that after the recent change https://github.com/QuantConnect/Lean/pull/5145 the `Platform target` for the launcher/toolbox/report in master is `x86` for the AnyCpu/debug or release build configurations. While previously it was `AnyCpu`. We will fix this ASAP @C-SELLERS.

**Comment by TightLinesOfCode** [comment]
@Martin-Molinero  @C-SELLERS    One of the issues I ran into is the massively parallel downloads of data which easily grow larger than the small address space of 32-bit compilation.   Also, for speed increases, the 64-bit will have a dramatic increase later when the the code is refactored for speed.   This becomes especially true for the back testing engine when a user might want to keep 8000 tickers in memory for large scale AI pipelines and computation.

But generally, since 32-bit compilation is for backward compatibility, it doesn't really make sense to have it for high performance code.

**Comment by jaredbroad** [comment]
> But generally, since 32-bit compilation is for backward compatibility, it doesn't really make sense to have it for high-performance code.

I think @Martin-Molinero 's point is specifically AnyCPU runs in x64 when it's available, and the research above points to that there is no speed up as it's already running in x64 when it's available.

**Comment by TightLinesOfCode** [comment]
The platform target is set to x86 and the main problem is the addressable memory space.    For large data analysis, the x86 default will cause a problem.       It's not just about speed, except when windows has to swap memory out from disk.

**Pull request closed without merging**
