### PR TITLE
Processing speed improvement

### PR DESCRIPTION
**Pull request by StefanoRaggi**
My benchmark algorithm went from 200k ticks/sec to 300k ticks/sec

### CODE REVIEW

**Comment by mchandschuh** [comment]
Are you able to share the algo used to perform the benchmarking?

**Comment by StefanoRaggi** [comment]
public class BasicTemplateAlgorithm : QCAlgorithm
    {
        private int _ticksProcessed = 0;

        //Initialize the data and resolution you require for your strategy:
        public override void Initialize()
        {
            //Start and End Date range for the backtest:
            SetStartDate(2015, 1, 1);
            SetEndDate(2015, 5, 15);

            //Cash allocation
            SetCash(10000);

            AddSecurity(SecurityType.Forex, "EURUSD", Resolution.Tick);
        }

        public override void OnEndOfAlgorithm()
        {
            Debug("Total ticks processed: " + _ticksProcessed);
        }

        public void OnData(Ticks data)
        {
            _ticksProcessed += data.Count;
        }
    }

**Comment by StefanoRaggi** [comment]
The zip data files were generated from tick data downloaded and converted.

**Comment by mchandschuh** [comment]
While I was unable to see the massive speed improvement you saw, I was able to see very slight improvements. I think this is a good change. Thanks @StefanoRaggi

**Pull request merged**
