### PR TITLE
change HeikinAshi to inherit BarIndicator class.

### LINKED ISSUE #1286: Make HeikinAshi indicator work with QuoteBars
## Problem

Unable to use the HeikinAshi with QuoteBar Securities (e.g. Forex)

## Reproduce

```
ha = self.HeikinAshi("EURUSD")

# Error: Type mismatch found between consolidator and indicator for symbol: 
#   EURUSD.Consolidator outputs type QuoteBar but indicator expects input type TradeBar

```

## Proposed Solution

As far as I can tell, there is no reason we cannot have the HeikinAshi indicator work with QuoteBar. Would it be as simple as changing the inherited class from `TradeBarIndicator` to `BarIndicator`?

```
# Lean/Indicators/HeikinAshi.cs

namespace QuantConnect.Indicators
{
    public class HeikinAshi : BarIndicator
```

### PR DESCRIPTION
**Pull request by jcandan**
closes #1286.

### CODE REVIEW

**Comment by mchandschuh** [comment]
This branch does not build.

```
HeikinAshi.cs(99,36): error CS0115: 'HeikinAshi.ComputeNextValue(TradeBar)': no suitable method found to override
HeikinAshi.cs(29,18): error CS0534: 'HeikinAshi' does not implement inherited abstract member 'IndicatorBase<IBaseDataBar>.ComputeNextValue(IBaseDataBar)'
```

**Comment by jcandan** [comment]
Yeah, I just wanted to get the ball rolling. I'm not super familiar yet with Lean's code base, mono, or C#. I don't know what to do with `Volume.Update(new IndicatorDataPoint(input.Time, input.Volume));`. If this is necessary for Securities with Volume, how might we still provide this update for them, but still service QuoteBar securities like Forex?

**Comment by jaredbroad** [comment]
Thank you for the effort & first steps @jcandan but please iterate in your own branch; then rebase to catch up with all the commits since your branch; then submit a PR which passes build tests.

WIP PR's aren't encouraged as they email everyone who stars the repo generating unnecessary spam.

**Comment by jcandan** [comment]
@jaredbroad, understood. thanks.

**Comment by Worthy7** [comment]
@jcandan status update please

**Pull request closed without merging**
