### PR TITLE
Add BidSize and AskSize to Tick

### PR DESCRIPTION
**Pull request by AlexCatarino**
Working on the Options Project, I made this little change.
If this is merged, it would close issue #118.

### CODE REVIEW

**Comment by mchandschuh** [comment]
@AlexCatarino - I can pull in the addition of bid/ask size to the `Tick` class, but the other change I think needs more thought, it will affect everything in our system. If possible, continue on the options stuff without considering the IContract concept. We'll need to fully flesh out the contract system before coding it up.

**Comment by mchandschuh** [comment]
The first commit (with edits) was merged in https://github.com/QuantConnect/Lean/commit/942d3fc7723bf5c61af391bb32e2a82a452462f2

**Comment by AlexCatarino** [comment]
Ok, but we need to define how IContract will be.
I used this additions to rewrite the AlgoSeek Options Converter and the LeanDataWriter.

**Comment by mchandschuh** [comment]
Understandable, you can keep working with what you have, but I'll need more time to implement it properly throughout the entire code base since it can have far reaching implications, this is something I don't want to rush.

If required, make some temporary classes that represent the data you need and where you need it and we can refactor it later when a full-fledged contract system is implemented in Lean.

**Pull request closed without merging**
