### PR TITLE
Add new Market.CFE

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
As most brokers use separate exchange codes for `CBOE` and `CFE`, we added the new `Market.CFE` (previously `Market.CBOE` was used for both exchanges). 

#### Related Issue
n/a

#### Motivation and Context
- Easier to handle symbol mapping for new brokerages.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
- Existing unit tests
- Live testing with IB

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by Martin-Molinero — COMMENTED** [review]
Seems we are replacing Market.CBOE for Market.CFE is it not valid anymore for any of these cases though?

**Comment by StefanoRaggi** [comment]
> Seems we are replacing Market.CBOE for Market.CFE is it not valid anymore for any of these cases though?

I think we still need to keep `Market.CBOE` for options?

**Review by gsalaz98 — APPROVED** [review]
> 
> 
> > Seems we are replacing Market.CBOE for Market.CFE is it not valid anymore for any of these cases though?
> 
> I think we still need to keep `Market.CBOE` for options?

We require `Market.CBOE` for index options IB live trading support.

PR Looks good 👍 - seems these changes are only isolated to futures, though a quick manual live test of VX futures options would be nice if possible.

**Review by Martin-Molinero — COMMENTED** [review]
Cool 👍
Believe merging this one will require moving existing data around and making sure new data is also placed in the correct location

**Pull request merged**
