### PR TITLE
Update Binance currency pairs

### LINKED ISSUE #7692: Add FDUSD-Quoted Crypto Pairs
#### Expected Behavior
The following pairs are listed for Binance:
- "ADAFDUSD"
- "LTCFDUSD"
- "DOTFDUSD"
- "MATICFDUSD"
- "SHIBFDUSD"
- "AVAXFDUSD"
- "FILFDUSD"
- "LTCFDUSD"
- "ATOMFDUSD"
- "BCHFDUSD"
- "ALGOFDUSD"
- "FTMFDUSD"
- "LINKFDUSD"
- "NEARFDUSD"
See https://www.binance.com/api/v3/exchangeInfo

#### Actual Behavior
Some of these pairs are not included.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by starteleport**
#### Description
This adds missing Binance symbols to the symbol database.

#### Related Issue
Closes #7692

#### Motivation and Context
Some existing Binance trading pairs were absent in the symbol database.

#### Requires Documentation Change
No

#### How Has This Been Tested?
This is the metadata change only, so I suppose there is no need to run tests.

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] Added tests for new stablecoin, fixed existing.
- [x] All existing tests are passing.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by AlexCatarino** [comment]
We also have a request for GBP-quoted crypto pairs. It's out of the scope of the issue that led to this pull request, but we could add a commit to address it too.

**Comment by starteleport** [comment]
Actually yes, it's not a complete list of the pairs that are absent. If it's okay to go out of scope here, I could add a broader range of crypto pairs (i.e. all that are absent at the moment)

**Comment by Martin-Molinero** [comment]
Hey @starteleport ! Thank you for the contribution,
Running the binance toolbox updater will generate the new complete SPDB automatically based on their api see https://github.com/QuantConnect/Lean.Brokerages.Binance/blob/master/QuantConnect.BinanceBrokerage.ToolBox/Program.cs#L70

**Comment by starteleport** [comment]
@Martin-Molinero done!

**Review by jhonabreul — CHANGES_REQUESTED** [review]
Thank you for your contribution! Looks good. Just one comment: why the changes in the Kraken symbols?

**Comment by Martin-Molinero** [comment]
Thank you @starteleport! Almost there, please revert the kraken SPDB changes like JA noted 👍. There seems to be a few unit tests failing in the PR, possibly related to that change

**Comment by starteleport** [comment]
Ah, sorry for Kraken bits, they were supposed to be rolled back.

**Comment by starteleport** [comment]
Also, I'm looking into the failing tests now

**Review by Martin-Molinero — APPROVED** [review]
Nice work! 🚀

**Review by jhonabreul — APPROVED** [review]
Thank you!

**Comment by starteleport** [comment]
@Martin-Molinero, could you review again, please? I've fixed a typo in a symbol name.

**Comment by starteleport** [comment]
That's kind of strange. I have `OptionChainProviderTests.LiveOptionChainProviderReturnsFutureOptionData` failing locally and in my GH fork. 

I'm not sure about the reasons, because this seems unrelated. Any ideas? If not, I'll look into that a bit later.

**Comment by starteleport** [comment]
It looks like the API used during the test is failing:
```
20240123 20:28:02.303 ERROR:: <GetFutureOptionContractList>d__15.MoveNext(): Failed to retrieve futures options chain from CME, returning empty result (5 / 5) System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
```

Given that there had been quite a few test runs of this test recently, and the throttling inside `GetFutureOptionContractList`, I suspect that we have hit some rate limiting of the called API.

**Review by Martin-Molinero — APPROVED** [review]

**Comment by Martin-Molinero** [comment]
> It looks like the API used during the test is failing:
> 
> ```
> 20240123 20:28:02.303 ERROR:: <GetFutureOptionContractList>d__15.MoveNext(): Failed to retrieve futures options chain from CME, returning empty result (5 / 5) System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
> ```
> 
> Given that there had been quite a few test runs of this test recently, and the throttling inside `GetFutureOptionContractList`, I suspect that we have hit some rate limiting of the called API.

Hey @starteleport! Thank you 🚢
Yes, that unit test has started failing on and off for github CI, unrelated 👍

**Pull request merged**
