### PR TITLE
Remove run script's coreutils dependency (Closes #4809)

### LINKED ISSUE #4809: Docker run script fails on systems without coreutils (realpath)
#### Expected Behavior
Relative paths should normalize at the prompts.

#### Actual Behavior
Crashes because realpath isn't available.

#### Potential Solution
Polyfill.

#### Reproducing the Problem
Run on macOS or old Debian.

#### System Information
macOS Big Sur

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by kazazes**
#### Description
- Removed dependency on `realpath`, notably absent from macOS and some debian distros. Replaced with an equivalent bash function.
- Cleaned up prompt response handling, replaced var tests with param expressions.
- Removed potentially uneeded calls to sudo (again absent on some systems and most users are part of the docker group anyway). Instead, test if it's needed and get preauth with sudo -v.
- Poll for running and stopped Lean containers, and prompt before replacing them. Would fail prior.
- Uppercase variables. Sorry.
- Incidentally fixed some state-related bug with config file location. Sounds like #4592

#### Related Issue
#4809

#### Requires Documentation Change
None

#### How Has This Been Tested?
Tested on macOS and Ubuntu 20. Needs to be run with `CSHARP_DLL` set for full coverage.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Review by C-SELLERS — CHANGES_REQUESTED** [review]
Hey Kazazes, nice changes.

I like some of the cleanups as well as the handling of sudo privileges and already running lean containers. I am having some issues though on my home server running Ubuntu 20.04 with the default path mapping. Just running the script with all defaults here is the output:

```
colton@HomeServer:~/Desktop/Lean$ ./run_docker.sh
Docker image [default: quantconnect/lean:latest]:
Path to Lean config.json [default: ./Launcher/config.json]:
Path to Data directory [default: ./Data]:
Path to Results directory [default: ./Results]:
Path to Python directory [default: ./Algorithm.Python/]:
Would you like to debug C#? (Requires mono debugger attachment) [default: N]:
Error: No such container: LeanEngine
Launching LeanEngine with command:
sudo docker run --rm -v /home/colton/Desktop/Lean/Launcher/config.json:/Lean/Launcher/config.json:ro     -v /home/colton/Desktop/Lean/:/Data:ro     -v /home/colton/Desktop/Lean/:/Results     --name LeanEngine     -p 5678:5678 --mount type=bind,source=./Launcher/bin/Debug/QuantConnect.Algorithm.CSharp.dll,target=/Lean/Launcher/bin/Debug/QuantConnect.Algorithm.CSharp.dll     --mount type=bind,source=./Launcher/bin/Debug/QuantConnect.Algorithm.CSharp.pdb,target=/Lean/Launcher/bin/Debug/QuantConnect.Algorithm.CSharp.pdb -v /home/colton/Desktop/Lean/:/Lean/Algorithm.Python quantconnect/lean:latest --data-folder /Data --results-destination-folder /Results --config /Lean/Launcher/config.json
docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: './Launcher/bin/Debug/QuantConnect.Algorithm.CSharp.dll' mount path must be absolute.
See 'docker run --help'.
```

It seems like the config path is fine, but I am not sure why the volume path on Data, Results, and Algorithm.Python are all incorrect paths, there is also issues with the csharp dll and pdb files being mounted. We will need to be sure that this is corrected before moving forward.

Also I see you moved most binding statements to -v from --mount, from what I see it should be the same result but I was curious what your reasoning for the swap was?

Thanks again, looking forward to getting this into the repo!

**Comment by kazazes** [comment]
Hey C,

I will have another look at the path resolution, I may have mistranslated the `../../../` used in the container as relative to the Lean directory instead.

I swapped `--mount` for `-v` because mount was using the default mount options, which `-v` is an alias of.

**Comment by C-SELLERS** [comment]
Sounds good! 

Ah yes that makes sense, maybe we can change the CSharp DLL and PDB to use them as well!

**Comment by jaredbroad** [comment]
@kazazes thanks for the PR. 

A note for posterity, from our tests you need to use --mount with mounting files. -v is fine for directories.

**Comment by C-SELLERS** [comment]
PR Replaced by #4922

**Comment by Martin-Molinero** [comment]
Thanks @kazazes! I'm closing this PR since @C-SELLERS addressed reviews on top of this PR at https://github.com/QuantConnect/Lean/pull/4922

**Pull request closed without merging**
