### PR TITLE
Fix AlgorithmRunner.RunLocalBacktest

### PR DESCRIPTION
**Pull request by dpavlenkov**
Remove unnecessary acknowledgement, dispose properly of loghandler et all.

### CODE REVIEW

**Comment by dpavlenkov** [comment]
I need to look more at this. It's still not right.

**Comment by dpavlenkov** [comment]
I can run tests individually, but when more than one together, one completes and the other hangs. I can see that BrokerageTransactionHandler.Run() transaction thread is not running. So this needs more looking into.

**Comment by dpavlenkov** [comment]
Now all tests run together.

**Comment by mchandschuh** [comment]
Awesome stuff @dpavlenkov!!

Merged in https://github.com/QuantConnect/Lean/commit/78d21b0d75ea0c060d1f092153ea4e5b443d8ece

**Pull request closed without merging**
