### PR TITLE
Refreshed XAUUSD sample data after data sync

### LINKED ISSUE #2965: XAUUSD sample data needs a refresh
#### Expected Behavior
XAUUSD (OANDA, minute) sample data matches what is downloaded from the repository.

#### Actual Behavior
XAUUSD sample data does not match what is downloaded from the repository since this was refreshed recently by @Jay-Jay-D .

#### Potential Solution
Commit the refreshed sample data zip's - I'm posting a PR.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### PR DESCRIPTION
**Pull request by Doggie52**
#### Description
OANDA's CFD minute data repository was refreshed recently to clear out old data issues, as per hard work from @Jay-Jay-D . This commit brings Lean's sample data for `XAUUSD` in line with these changes.

#### Related Issue
Closes #2965

#### Motivation and Context
Sample data should be in line with what's available in the repository for obvious reasons.

#### How Has This Been Tested?
I cleared out all XAUUSD data and had it redownloaded, it was then I spotted the changes. I have not gone through and checked each file to see what is different in the data.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`
**The contributing guidelines

### CODE REVIEW

**Comment by AlexCatarino** [comment]
Thanks, @Doggie52. This pull request only updates minute-resolution XAUUSD data and need to update other resolutions to achieve data consistency.

**Comment by Doggie52** [comment]
Wasn't aware there had been any changes to the other resolutions. I'll go ahead and update those too.

**Comment by Doggie52** [comment]
Actually, won't be able to update those myself as I can't download second and tick resolutions locally.

I have updated `daily` and `hour` data. As far as I can see, the last commit updating these was up to the date of the commit, so I have done the same here (i.e. updating them till 26 Feb 2018).

**Comment by Doggie52** [comment]
Reason for the force-push: had accidentally put 2018 in the commit message, apologies!

**Pull request merged**
